# Auto deploy repo from Github to Amazon S3 bucket via Travis CI
# * Set env vars for ACCESS_KEY_ID, BUCKET_NAME and SECRET_ACCESS_KEY on Travis 
# * Update `bucket.name` in `sync` command
# * Assumes your `publishDir` is the default (`public`) - if not update `sync` command

language: go
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
    - awscli
install: go get -v github.com/spf13/hugo
env:
  - AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
script:
  - hugo
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $BUCKET_NAME
  skip_cleanup: true
  acl: private
  region: eu-central-1
  local_dir: public
  detect_encoding: true

# fix wrong mime types
after_deploy:
  - aws s3 cp --recursive s3://$BUCKET_NAME/ s3://$BUCKET_NAME/ --exclude "*" --include "*.json" --content-type "application/json" --metadata-directive "REPLACE"
  - aws s3 cp --recursive s3://$BUCKET_NAME/ s3://$BUCKET_NAME/ --exclude "*" --include "*.css" --content-type "text/css" --metadata-directive "REPLACE"
  - aws s3 cp --recursive s3://$BUCKET_NAME/ s3://$BUCKET_NAME/ --exclude "*" --include "*.js" --content-type "application/javascript" --metadata-directive "REPLACE"

notifications:
    email: true
