---
# Auto deploy repo from Github to Amazon S3 bucket via Travis CI
# * Set env vars for ACCESS_KEY_ID, BUCKET_NAME and SECRET_ACCESS_KEY on Travis
# * Update `bucket.name` in `sync` command
# * Assumes your `publishDir` is the default (`public`
# ) - if not update `sync` command

language: go
os: linux
dist: bionic


env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.65.3

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - hugo

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $BUCKET_NAME
  skip_cleanup: true
  acl: private
  region: eu-central-1
  local_dir: public
  detect_encoding: true

# fix wrong mime types
after_deploy:
  - pip install --user awscli
  - ~/.local/bin/aws s3 cp --recursive s3://$BUCKET_NAME/ s3://$BUCKET_NAME/ --exclude "*" --include "*.json" --content-type "application/json" --metadata-directive "REPLACE"
  - ~/.local/bin/aws s3 cp --recursive s3://$BUCKET_NAME/ s3://$BUCKET_NAME/ --exclude "*" --include "*.css" --content-type "text/css" --metadata-directive "REPLACE"
  - ~/.local/bin/aws s3 cp --recursive s3://$BUCKET_NAME/ s3://$BUCKET_NAME/ --exclude "*" --include "*.js" --content-type "application/javascript" --metadata-directive "REPLACE"

notifications:
    email: true
